-- MySQL Script generated by MySQL Workbench
-- 01/06/15 15:59:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema prop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prop` ;

-- -----------------------------------------------------
-- Schema prop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prop` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`terrenos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`terrenos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`terrenos` (
  `idterrenos` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terreno_m 2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `ideal` VARCHAR(45) NULL,
  `uso_suelo` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idterrenos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departametos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`departametos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`departametos` (
  `iddepartametos` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terreno_m2` VARCHAR(45) NULL,
  `construccion_m2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `recamaras` VARCHAR(45) NULL,
  `banos` VARCHAR(45) NULL,
  `espacio_autos` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `condicion` VARCHAR(45) NULL,
  `credito` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `piso_planta` VARCHAR(45) NULL,
  `elevador` VARCHAR(45) NULL,
  `linea_telefonica` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `tv_cable` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`iddepartametos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bodegas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bodegas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bodegas` (
  `idbodega` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terreno_m2` VARCHAR(45) NULL,
  `construccion_m2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `altura_m` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `condicion` VARCHAR(45) NULL,
  `banos` VARCHAR(45) NULL,
  `ideal` VARCHAR(45) NULL,
  `estacionamiento` VARCHAR(45) NULL,
  `patio_maniobras` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `vigilancia` VARCHAR(45) NULL,
  `montacarga` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idbodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oficinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oficinas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oficinas` (
  `idoficina` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terrno_m2` VARCHAR(45) NULL,
  `construccion_m2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `espacio_autos` VARCHAR(45) NULL,
  `sala_juntas` VARCHAR(45) NULL,
  `numero_usuarios` VARCHAR(45) NULL,
  `banos` VARCHAR(45) NULL,
  `recepcion` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `uso_suelo` VARCHAR(45) NULL,
  `piso_planta` VARCHAR(45) NULL,
  `elevador` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `linea_telefonica` VARCHAR(45) NULL,
  `cafeteria` VARCHAR(45) NULL,
  `seguridad_privada` VARCHAR(45) NULL,
  `mantenimiento` VARCHAR(45) NULL,
  `recepcion` VARCHAR(45) NULL,
  `aire_acondicionado` VARCHAR(45) NULL,
  `alarma` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idoficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locales` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locales` (
  `idlocal` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terreno_m2` VARCHAR(45) NULL,
  `construccion_m2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `espacio_autos` VARCHAR(45) NULL,
  `banos` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `acondicionado_para` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `linea_telefonica` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idlocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nave_industrial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nave_industrial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nave_industrial` (
  `idnave_industrial` INT NOT NULL,
  `terreno_m2` VARCHAR(45) NULL,
  `construccion_m2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `condicion` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `ideal_para` VARCHAR(45) NULL,
  `oficina` VARCHAR(45) NULL,
  `banos` VARCHAR(45) NULL,
  `patio_maniobras` VARCHAR(45) NULL,
  `equipado` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idnave_industrial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rancho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rancho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rancho` (
  `idrancho` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terreno_m2` VARCHAR(45) NULL,
  `contruccion_m2` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL,
  `direccion_numero` VARCHAR(45) NULL,
  `direccion_municipio` VARCHAR(45) NULL,
  `direccion_colonia` VARCHAR(45) NULL,
  `direccion_estado` VARCHAR(45) NULL,
  `direccion_codigo_postal` VARCHAR(45) NULL,
  `direccion_pais` VARCHAR(45) NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `recamaras` VARCHAR(45) NULL,
  `banos` VARCHAR(45) NULL,
  `corrales` VARCHAR(45) NULL,
  `gallineros` VARCHAR(45) NULL,
  `caballerizas` VARCHAR(45) NULL,
  `invernaderos` VARCHAR(45) NULL,
  `bodegas` VARCHAR(45) NULL,
  `casas` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `linea_telefonica` VARCHAR(45) NULL,
  `gimnasio` VARCHAR(45) NULL,
  `canchas_deportivas` VARCHAR(45) NULL,
  `alberca` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL,
  `contacto_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idrancho`))
ENGINE = InnoDB;

USE `prop` ;

-- -----------------------------------------------------
-- Table `prop`.`casas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prop`.`casas` ;

CREATE TABLE IF NOT EXISTS `prop`.`casas` (
  `idcasa` INT NOT NULL,
  `venta_renta` VARCHAR(45) NULL,
  `terreno_m2` VARCHAR(45) NULL DEFAULT NULL,
  `construccion_m2` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL,
  `direccion_calle` VARCHAR(45) NULL DEFAULT NULL,
  `direccion_numero` INT NULL DEFAULT NULL,
  `direccion_colonia` VARCHAR(45) NULL DEFAULT NULL,
  `direccion_municipio` VARCHAR(45) NULL DEFAULT NULL,
  `direccion_estado` VARCHAR(45) NULL DEFAULT NULL,
  `direccion_codigo_postal` INT NULL DEFAULT NULL,
  `direccion_pais` VARCHAR(45) NULL DEFAULT NULL,
  `direccion_latitud` VARCHAR(45) NULL,
  `direccion_longitud` VARCHAR(45) NULL,
  `recamaras` INT NULL DEFAULT NULL,
  `banos` INT NULL DEFAULT NULL,
  `balcon` TINYINT(1) NULL DEFAULT NULL,
  `patios` INT NULL DEFAULT NULL,
  `espacio_autos` INT NULL DEFAULT NULL,
  `condicion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` VARCHAR(10) NULL DEFAULT NULL,
  `credito` TINYINT(1) NULL DEFAULT NULL,
  `casascol` VARCHAR(45) NULL DEFAULT NULL,
  `agua` VARCHAR(45) NULL,
  `drenaje` VARCHAR(45) NULL,
  `luz` VARCHAR(45) NULL,
  `linea_telefonica` VARCHAR(45) NULL,
  `internet` VARCHAR(45) NULL,
  `tv_cable` VARCHAR(45) NULL,
  `accesos` VARCHAR(45) NULL,
  `amueblada` VARCHAR(45) NULL,
  `cocina_equipada` VARCHAR(45) NULL,
  `closets` VARCHAR(45) NULL,
  `alberca` VARCHAR(45) NULL,
  `vista_panoramica` VARCHAR(45) NULL,
  `salon_juegos` VARCHAR(45) NULL,
  `vigilancia_privada` VARCHAR(45) NULL,
  `mantenimiento` VARCHAR(45) NULL,
  `zona_arbolada` VARCHAR(45) NULL,
  `escuelas_cercanas` VARCHAR(45) NULL,
  `gimnacios_cercanos` VARCHAR(45) NULL,
  `parques_cercanos` VARCHAR(45) NULL,
  `contacto_telefono` VARCHAR(45) NULL DEFAULT NULL,
  `contacto_email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcasa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
